### ISSUE TITLE
imshow inside container

### ISSUE THREAD

**Issue by alexnix** [janza/docker-python3-opencv#13]
How to use imshow from inside container?

I am getting the following error:
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opencv-3.4.0/modules/highgui/src/window.cpp, line 611
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /opencv-3.4.0/modules/highgui/src/window.cpp:611: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

**Comment by janza** [comment]
This image doesn't support that. You would need to extend the image by installing the right library (libgtk2.0-dev) as instructed in the error, and then use one of the ways described in [this thread](https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container) to get it to display on your linux machine.
