### ISSUE TITLE
Unable to locate package libjasper-dev

### ISSUE THREAD

**Issue by MarcDuQuesne** [janza/docker-python3-opencv#16]
Upon trying to build the image, with:
`docker build -t 'opencv' .`

I get E: Unable to locate package libjasper-dev

according to:
https://stackoverflow.com/questions/43484357/opencv-in-ubuntu-17-04/44488374#44488374
one should add some repository. This solution did not work for me.

**Comment by MattMCloudy** [comment]
I edited the Dockerfile to install jasper by cloning the repo. I deleted the libjasper-dev install in apt-get then added this:

`RUN git clone https://github.com/jasperproject/jasper-client.git jasper \
&& chmod +x jasper/jasper.py \
&& pip install --upgrade setuptools \
&& pip install -r jasper/client/requirements.txt`

**Comment by chugreevd** [comment]
Works with base Python image pointing to older Debian
`FROM python:3.6` -> `FROM python:3.6-jessie`

**Comment by tchebraga** [comment]
@MattMCloudy Tks for your post, in my case I just had to change the sintax in DockerFile to:
```
RUN git clone https://github.com/jasperproject/jasper-client.git jasper && \
 		chmod +x jasper/jasper.py && \
		pip install --upgrade setuptools && \ 
		pip install -r jasper/client/requirements.txt
```

**Comment by janza** [comment]
Removed that package and support for jpeg2000 d5ac3036e789d3208faa55b708be7896dbd9b011 so this is no longer an issue.

**Comment by yustiks** [comment]
I have the same issue when I try to install opencv. 
```
E: Unable to locate package libjasper-dev
```

**Comment by yustiks** [comment]
> @MattMCloudy Tks for your post, in my case I just had to change the sintax in DockerFile to:
> 
> ```
> RUN git clone https://github.com/jasperproject/jasper-client.git jasper && \
>  		chmod +x jasper/jasper.py && \
> 		pip install --upgrade setuptools && \ 
> 		pip install -r jasper/client/requirements.txt
> ```

I tried to run your command in terminal and got this error: 
```
ERROR: tensorflow-estimator 1.13.0 has requirement mock>=2.0.0, but you'll have mock 1.0.1 which is incompatible.
ERROR: pandas 0.24.2 has requirement python-dateutil>=2.5.0, but you'll have python-dateutil 2.3 which is incompatible.
```
