### ISSUE TITLE
Run Gui windows

### ISSUE THREAD

**Issue by miltonlab** [janza/docker-python3-opencv#17]
Dear janza, i have this error:

> error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

When use things with windows, what can i do please?

**Comment by janza** [comment]
This docker images doesn't support GUI applications. 
I'll have to build a new image with the right configuration to support gtk.
