### ISSUE TITLE
Add Python 3.7 support

### ISSUE THREAD

**Issue by Jdban** [janza/docker-python3-opencv#18]
I tried myself and couldn't get it working. The jasper lib has issues and I didn't get too far

**Comment by janza** [comment]
Will have a look into this soon

**Comment by janza** [comment]
Python 3.7 + OpenCV 3.4.2 version is available with the latest version of the image

**Comment by Jdban** [comment]
![image](https://media.tenor.com/images/667d842fb2b5b51ba7da5e9940bc8747/tenor.gif)
