### ISSUE TITLE
Create image with previous version of contrib

### ISSUE THREAD

**Issue by PuneetKohli** [janza/docker-python3-opencv#19]
We've been using your docker image for our testing and noticed our code started failing today on automated builds due to the upgrade.

We reverted to `contrib-opencv-3.4.1` but that has an older version of cmake.

Can you release a version of contrib which was pushed 3 months ago in August?

**Comment by janza** [comment]
I think that was `contrib-opencv-3.4.2`, it's currently building on docker hub should be available soon

**Comment by PuneetKohli** [comment]
Thanks, using this build fixed our issue!
