### ISSUE TITLE
OpenCV 4.0.1

### ISSUE THREAD

**Issue by dnstanciu** [janza/docker-python3-opencv#25]
To use OpenCV 4.0.1 instead of 4.0.0, is it just a matter of changing the `OPENCV_VERSION` variable?

I could submit a pull request.

Thanks.

**Comment by janza** [comment]
Correct. I'll be happy to merge it

**Comment by dnstanciu** [comment]
@janza Cool, will do ASAP.

One more unrelated question. I see you're pulling from python:3.7 as a base image. When I go in the container, the version of Python that I get is 3.7.1, but on the DockerHub page, it says it should be 3.7.2.

Do you know why this is happening?

**Comment by janza** [comment]
It's because image was built before 3.7.2 was released. After we update opencv version, a new image will be built with the latest python version

**Comment by dnstanciu** [comment]
That makes sense, thanks. I've submitted a PR, but I'm not sure how to port the change to the contrib branch. I've asked about that on the PR itself, so I'll close this issue. Thanks for the repo!
