### ISSUE TITLE
Can you give me the file ippicv_linux_20151201.tgz?

### ISSUE THREAD

**Issue by 9599** [janza/docker-python3-opencv#6]
When I set the same configure of you,there is an error about downloading the file ippicv_linux_20151201.tgz. Could you push the file to the github?

**Comment by janza** [comment]
I'm not sure what you mean by configure but i guess you want these files: https://github.com/opencv/opencv_3rdparty/tree/ippicv/master_20151201/ippicv ?

**Comment by 9599** [comment]
Sorry,I guess there is exactly an error when I use the container.When I use the container,and type "docker run -it yaya/python-opencv:3.2 /bin/bash"to enter the  interactive interface,and type"python import cv2",there is an error that Illegal instruction (core dumped).What's the matter about the image?Could you tell me the reason and help me to fix it ?

**Comment by janza** [comment]
I guess you are trying to use this container on a hardware that doesn't support Intel's IPP. You can try modifying the Dockerfile in this repository without the `-DWITH_IPP=ON` option and then building the
image.

Let me know if that works, I can create a tagged version of the image with these extensions disabled.

**Comment by janza** [comment]
Closing as there was no response
