### ISSUE TITLE
docker support GUI?

### ISSUE THREAD

**Issue by scotthuang1989** [janza/docker-python3-opencv#7]
maybe this is a very silly question. I think docker can't have GUI. so any gui related function should not work with this docker  image?

**Comment by janza** [comment]
You could setup X forwarding with sshd or share X11's socket to the host machine. This [stackoverflow thread](https://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers) has some information on how to do that. You might need to modify this image to get X support though.

**Comment by scotthuang1989** [comment]
looks great. thanks.
