### ISSUE TITLE
cannot find zipfile directory 

### ISSUE THREAD

**Issue by liferlisiqi** [janza/docker-python3-opencv#8]
unzip:  cannot find zipfile directory in one of 3.4.0.zip or 3.4.0.zip.zip, and cannot find 3.4.0.zip.ZIP, period.

**Comment by janza** [comment]
Cna you provide more information. I don't see any issue on docker hub build: https://hub.docker.com/r/jjanzic/docker-python3-opencv/builds/bmvrxblsc3rbnahnssc9drs/

**Comment by liferlisiqi** [comment]
My error, I use curl to download openCV source code, lead to this problem. When I use wget, no problem. Thank you.
